Improve git hooks to fail on particular stages

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -2,29 +2,52 @@
 RED="\033[1;31m"
 GREEN="\033[1;32m"
 NC="\033[0m"
-linter_exit_code=1
+exit_code=1
 
 all_ts_files=$(git diff --cached --diff-filter=d --name-only | grep .ts$)
 all_tsx_files=$(git diff --cached --diff-filter=d --name-only | grep .tsx$)
 
+
 echo "${NC}Checking for Typescript errors"
 npx tsc --noEmit
+
+exit_code=$?
+
+if [ $exit_code -ne 0 ]
+then
+  echo "${RED} ❌ Errors have occurred during Typescript type checking"
+  exit 1
+else
+  echo "${GREEN} ✔ Typescript checks succeeded"
+fi
+
 
 echo "${NC}Linting with ESLint and Prettier"
 lerna run lint
 
+exit_code=$?
+
+if [ $exit_code -ne 0 ]
+then
+  echo "${RED} ❌ Errors have occurred during linting"
+  exit 1
+else
+  echo "${GREEN} ✔ Eslint linting successful"
+fi
+
+
 echo "${NC}Running tests on changed files"
 lerna run test -- --bail --findRelatedTests
 
-linter_exit_code=$?
+exit_code=$?
 
-git add -f $all_ts_files $all_tsx_files
-
-if [ $linter_exit_code -ne 0 ]
+if [ $exit_code -ne 0 ]
 then
-  echo "${RED} ❌ Errors have occurred during pre-commit checks"
+  echo "${RED} ❌ Errors have occurred during tests"
   exit 1
 else
-  echo "${GREEN} ✔ Typescript and Eslint did not find any errors"
-  exit 0
+  echo "${GREEN} ✔ Tests are fine"
 fi
+
+git add -f $all_ts_files $all_tsx_files
+exit 0
